# Generated by Django 5.0 on 2024-01-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='offerDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
